### ISSUE TITLE
compile fails on case sensitive file system 

### ISSUE THREAD

**Issue by j3tm0t0** [Seeed-Studio/Wio_LTE_Arduino_Library#1]
In my environment (macOS High Sierra on case-sensitive APFS volume), I encountered compile error like following.

```
In file included from /Users/moto/Documents/Arduino/libraries/WioLTEforArduino-1.0.5/WioLTEforArduino.h:5:0,
                 from /Users/moto/Documents/Arduino/libraries/WioLTEforArduino-1.0.5/examples/soracom/soracom-harvest/soracom-harvest.ino:1:
/Users/moto/Library/Arduino15/packages/Seeeduino/hardware/Seeed_STM32F4/1.1.1/libraries/WS2812/Seeed_ws2812.h:35:21: fatal error: arduino.h: No such file or directory
 #include <arduino.h>
                     ^
compilation terminated.
exit status 1
```

On case-insensitive environments like Windows or default macOS setting, "Arduino.h" can be accessed by "arduino.h", but on case-sensitive environments(like Linux or macOS with case-sensitive files system) it can't.

Please fix the include lines in Seeed_ws2812.cpp and h.

**Comment by lanselambor** [comment]
Thank you, have merged it.
