### ISSUE TITLE
Japan lib vs global lib 

### ISSUE THREAD

**Issue by salmanfarisvp** [Seeed-Studio/Wio_LTE_Arduino_Library#10]
What is the difference between #include <WioLTEforArduino.h> (Japan Version https://github.com/SeeedJP/WioLTEforArduino) and the Wio_LTE_Arduino_Library (this repo https://github.com/Seeed-Studio/Wio_LTE_Arduino_Library).

**Comment by Pillar1989** [comment]
We only have one repository, https://github.com/Seeed-Studio/Wio_LTE_Arduino_Library

**Comment by salmanfarisvp** [comment]
So what about this one https://github.com/SeeedJP/WioLTEforArduino

**Comment by Pillar1989** [comment]
I'm not sure. I might need to find out
