### ISSUE TITLE
GNSS never connecting

### ISSUE THREAD

**Issue by cskonopka** [Seeed-Studio/Wio_LTE_Arduino_Library#7]
I've tested the GNSS_Show_Coordinate example with several Wio LTE's and none of them connect/provide GPS coordinates. I dug a little deeper and received a very vague error, "not fixed now".

``` AT+QGPS LOC? +CME ERROR: 516 ```

Kinda comical actually.

How you successfully run this example?

**Comment by lanselambor** [comment]
@cskonopka Please make sure testing outside the house, so that GPS signal can be received.
Or
If you are using EC21-J module, it may don't have GPS function.

**Comment by lanselambor** [comment]
@cskonopka Please make sure testing outside the house, so that GPS can

**Comment by cskonopka** [comment]
Gotcha. Thank you for the clarification!
